name: Test docker inside docker
on:
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
      url:
        description: 'Ignore'
        required: false

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    steps:
      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Quickstart
        run: |
          curl -L https://github.com/systemed/tilemaker/releases/download/v2.0.0/tilemaker-ubuntu-16.04.zip > tilemaker-ubuntu-16.04.zip
          unzip tilemaker-ubuntu-16.04.zip
          chmod +x build/tilemaker
          curl -L https://osmdata.openstreetmap.de/download/water-polygons-split-4326.zip  > water.zip
          unzip water.zip -d coastline
          mv coastline/water-polygons-split-4326/* coastline/
          ls -lh
          ls -lh coastline
          sed -i "s/name:latin/name/g" resources/process-openmaptiles.lua
          sed -i "s/name_int/name_en/g" resources/process-openmaptiles.lua
          cat resources/process-openmaptiles.lua
      - name: Generate tiles
        run: |
          curl -L http://download.geofabrik.de/australia-oceania/australia-latest.osm.pbf > australia.osm.pbf
          ls -lh
          ./build/tilemaker --input australia.osm.pbf --output australia.mbtiles --process resources/process-openmaptiles.lua --config resources/config-openmaptiles.json
          gzip australia.mbtiles
          ls -lh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            australia.mbtiles.gz
          tag_name: australia-tilemaker-nolatin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
