name: Test docker inside docker
on:
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
      url:
        description: 'Ignore'
        required: false

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          repository: 'openmaptiles/openmaptiles'

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Quickstart
        run: |
          sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

          sudo usermod -aG docker $(whoami)

          sudo apt-get install -y jq
          COMPOSE_VERSION=1.29.2

          sudo curl -L "https://github.com/docker/compose/releases/download/$COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Generate tiles
        run: |
          sed -i "/MIN_ZOOM=/c\MIN_ZOOM=13" .env
          sed -i "/MAX_ZOOM=/c\MAX_ZOOM=13" .env
          make
          ./quickstart.sh australia
          mv data/tiles.mbtiles australia.mbtiles
          gzip australia.mbtiles
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            australia.mbtiles.gz
          tag_name: australia13
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
