name: Tilemaker
on:
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
      url:
        description: 'Ignore'
        required: false

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: macos-latest
    steps:
      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Quickstart
        run: |
          curl -L https://github.com/systemed/tilemaker/releases/download/v2.1.0/tilemaker-macos-10.15.zip > tilemaker-macos-10.15.zip
          unzip tilemaker-macos-10.15.zip
          chmod +x build/tilemaker
          curl -L https://osmdata.openstreetmap.de/download/water-polygons-split-4326.zip  > water.zip
          unzip water.zip -d coastline
          mv coastline/water-polygons-split-4326/* coastline/
          ls -lh
          ls -lh coastline
          sed "s/preferred_language = nil/preferred_language = \"en\"/g" resources/process-openmaptiles.lua
          sed "s/name:latin/name:latin/g" resources/process-openmaptiles.lua
          sed "s/name_int/name:nonlatin/g" resources/process-openmaptiles.lua
          cat resources/process-openmaptiles.lua
      - name: Generate tiles
        run: |
          curl -L https://download.geofabrik.de/australia-oceania/australia-latest.osm.pbf > australia-oceania.osm.pbf
          ls -lh
          ./build/tilemaker --input australia-oceania.osm.pbf --output australia.mbtiles.gz --process resources/process-openmaptiles.lua --config resources/config-openmaptiles.json
          gzip australia.mbtiles.gz
          ls -lh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            australia.mbtiles.gz
          tag_name: australia-2022-03
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
